spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fairhold
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret: "fairhold-super-secret-key-for-jwt-authentication-minimum-256-bits"
  expiration: 3600000